server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: echo-gorm-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: echo-gorm-api
          __path__: /app/echo-gorm-api/app.log

    pipeline_stages:
      - json:
          expressions:
            msg: msg
            level: level
            method: method
            path: path
            status: status
            ip: ip
            userAgent: userAgent
            latency: latency
          drop_malformed: true
      - labels:
          level:
          method:
          status:
          path:
