server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: echo-gorm-api
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /Users/devsin/Desktop/AIDC/golang/echo-gorm-api-main/app.log
          app: echo-gorm-api 
          __path__: /var/log/echo-api/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: msg
            method: method
            path: path
            status: status
            ip: ip
            userAgent: userAgent
      - labels:
          level:
          method:
          status:
          path:
          app:
